grandppltedx: Implement custom version of SkColorPriv.h
- Our libui_ext depends on these defines. Therefore, Add a custom version of SkColorPriv.h

device/samsung/grandppltedx/mtk/graphics/ui_ext/lib/GraphicBufferUtil.cpp:94:23: error: use of undeclared identifier 'SkPacked16ToG32'
            wptr[1] = SkPacked16ToG32(c);

This reverts commit 1b8d0abb87505091c238f1a0fa3e49711d85b2a8.

Signed-off-by: Nguyễn Long <hoanglong.lumi404@gmail.com>